version: '3'

services:

  jenkins:

    image: jenkins/jenkins

    container_name: JenkinsSRV

    volumes:

      - ~/CSWebsite:/var/jenkins_home/Website

    user: root

    ports:

      - 8085:8080

      - 50001:50000

  tomcat:

    image: tomcat

    container_name: TomcatSRV

    volumes:

      - ~/CSWebsite:/usr/local/tomcat/webapps/CSWeb

    ports:

      - 8086:8080

  